

spring.data.mongodb.uri=mongodb+srv://sandeepsandyo9o7o1:ro45.200.100@cluster0.fjfmmcp.mongodb.net/blog?retryWrites=true&w=majority

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandeepprabhakula10@gmail.com
spring.mail.password=qsmpfmtjayvijvum
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true