global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['codeverse-chronicles.onrender.com']
    
        labels:
          application: 'spring-boot-app'
          environment: 'production'
    scrape_interval: 5s
    basic_auth:
      username: 'sandeep45.200.100@gmail.com'
      password: 'Rohitman45*'
